### ISSUE TITLE
Filenames: Enforce dash-cased.

### ISSUE THREAD

**Issue by ryan-roemer** [walmartlabs/eslint-config-defaults#17]
Enforce dash-cased.js for Walmart convention code.

See: https://github.com/FormidableLabs/formidable-react-component-boilerplate/pull/30 for example.

Base config:

```yml
---
"plugins":
  - "filenames"
"rules":
  "filenames/filenames": [2, "^[a-z\\-\\.]+$"] # dash-cased filenames.
```
